# Generated by Django 5.2.4 on 2025-08-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('project', 'Project'), ('participation', 'Class Participation'), ('homework', 'Homework'), ('test', 'Test')], help_text='Type of grade/assessment', max_length=20)),
                ('title', models.CharField(help_text="Title of the assignment/test (e.g., 'Math Quiz 1', 'History Essay')", max_length=200)),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by student', max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks possible', max_digits=6)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score (auto-calculated)', max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, choices=[('A+', 'A+ (97-100)'), ('A', 'A (93-96)'), ('A-', 'A- (90-92)'), ('B+', 'B+ (87-89)'), ('B', 'B (83-86)'), ('B-', 'B- (80-82)'), ('C+', 'C+ (77-79)'), ('C', 'C (73-76)'), ('C-', 'C- (70-72)'), ('D+', 'D+ (67-69)'), ('D', 'D (63-66)'), ('D-', 'D- (60-62)'), ('F', 'F (Below 60)')], help_text='Letter grade (auto-calculated)', max_length=2, null=True)),
                ('date_assigned', models.DateField(help_text='Date when assignment was given')),
                ('date_submitted', models.DateField(blank=True, help_text='Date when student submitted', null=True)),
                ('comments', models.TextField(blank=True, help_text="Teacher's comments/feedback", null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether grade is visible to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, help_text='Teacher who assigned this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_assigned', to='core.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date_assigned', 'subject', 'student'],
                'unique_together': {('student', 'subject', 'title', 'grade_type')},
            },
        ),
    ]
